/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#fffbff',
        'on-primary': '#ffffff',
        'secondary': '#6b38d4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#703700',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdcc5',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e9ddff',
        'outline-variant': '#c7c4d7',
        'on-error-container': '#93000a',
        'surface-bright': '#fcf8ff',
        'tertiary-container': '#b55d00',
        'surface-container': '#efecf8',
        'surface-dim': '#dbd8e4',
        'on-background': '#1b1b23',
        'on-secondary-fixed': '#23005c',
        'surface-tint': '#494bd6',
        'background': '#fcf8ff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#2f2ebe',
        'error': '#ba1a1a',
        'on-secondary-container': '#fffbff',
        'on-error': '#ffffff',
        'primary-fixed': '#e1e0ff',
        'surface-container-low': '#f5f2fe',
        'on-primary-fixed': '#07006c',
        'primary-container': '#6063ee',
        'tertiary-fixed-dim': '#ffb783',
        'secondary-container': '#8455ef',
        'inverse-primary': '#c0c1ff',
        'on-surface-variant': '#464554',
        'on-secondary': '#ffffff',
        'outline': '#767586',
        'surface-container-highest': '#e4e1ed',
        'surface-variant': '#e4e1ed',
        'secondary-fixed-dim': '#d0bcff',
        'on-tertiary-fixed': '#301400',
        'primary-fixed-dim': '#c0c1ff',
        'inverse-surface': '#303038',
        'surface': '#fcf8ff',
        'tertiary': '#904900',
        'primary': '#4648d4',
        'on-surface': '#1b1b23',
        'on-secondary-fixed-variant': '#5516be',
        'surface-container-high': '#e9e6f3',
        'inverse-on-surface': '#f2effb',
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      spacing: {
        'md': '16px',
        'gutter': '24px',
        'xl': '32px',
        'xs': '4px',
        'xxl': '48px',
        'sm': '8px',
        'base': '4px',
        'lg': '24px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
};
