import { STORAGE_KEYS } from '../constants';

const sampleInvoices = [
  {
    id: 'inv_seed_1',
    invoiceNumber: 'INV-0001',
    clientName: 'Acme Solutions',
    clientEmail: 'billing@acme.com',
    items: [
      { id: 'item_seed_1a', description: 'Brand Strategy & Identity', quantity: 1, rate: 8000, type: 'service' },
      { id: 'item_seed_1b', description: 'UI/UX Design - Dashboard', quantity: 45, rate: 100, type: 'service' },
    ],
    notes: 'Client requested Net-14 terms for this specific milestone.',
    paymentInstructions: 'Bank Transfer · Account: 123456789 · SWIFT: ACMEUS',
    dueDate: '2024-08-15',
    taxRate: 8,
    status: 'paid',
    createdAt: '2024-07-15T10:00:00.000Z',
  },
  {
    id: 'inv_seed_2',
    invoiceNumber: 'INV-0002',
    clientName: 'Nova Labs',
    clientEmail: 'finance@novalabs.io',
    items: [
      { id: 'item_seed_2a', description: 'Cloud Infrastructure Setup', quantity: 1, rate: 6200, type: 'service' },
      { id: 'item_seed_2b', description: 'DevOps Consultation (hours)', quantity: 20, rate: 100, type: 'service' },
    ],
    notes: '',
    paymentInstructions: '',
    dueDate: '2024-09-01',
    taxRate: 10,
    status: 'pending',
    createdAt: '2024-08-01T10:00:00.000Z',
  },
  {
    id: 'inv_seed_3',
    invoiceNumber: 'INV-0003',
    clientName: 'Quantum Design',
    clientEmail: 'hello@qdesign.co',
    items: [
      { id: 'item_seed_3a', description: 'Website Redesign', quantity: 1, rate: 3150, type: 'service' },
    ],
    notes: 'Includes responsive templates for all breakpoints.',
    paymentInstructions: 'ACH · Routing: 021000021 · Account: 987654321',
    dueDate: '2024-07-01',
    taxRate: 0,
    status: 'overdue',
    createdAt: '2024-06-10T10:00:00.000Z',
  },
  {
    id: 'inv_seed_4',
    invoiceNumber: 'INV-0004',
    clientName: 'Skyline Interactive',
    clientEmail: 'billing@skyline.io',
    items: [
      { id: 'item_seed_4a', description: 'Mobile App Development', quantity: 1, rate: 12450, type: 'service' },
    ],
    notes: 'Payment via bank transfer within 14 days.',
    paymentInstructions: 'Bank: FluxBank · Account: 456789123 · SWIFT: FLUXUS',
    dueDate: '2024-08-24',
    taxRate: 8,
    status: 'paid',
    createdAt: '2024-07-24T10:00:00.000Z',
  },
  {
    id: 'inv_seed_5',
    invoiceNumber: 'INV-0005',
    clientName: 'Apex Creative',
    clientEmail: 'studio@apexcreative.co',
    items: [
      { id: 'item_seed_5a', description: 'Social Media Campaign', quantity: 1, rate: 3200, type: 'service' },
      { id: 'item_seed_5b', description: 'Content Creation (posts)', quantity: 15, rate: 120, type: 'service' },
    ],
    notes: '',
    paymentInstructions: '',
    dueDate: '2025-08-05',
    taxRate: 5,
    status: 'pending',
    createdAt: '2024-07-05T10:00:00.000Z',
  },
  {
    id: 'inv_seed_6',
    invoiceNumber: 'INV-0006',
    clientName: 'Nova Peak',
    clientEmail: 'info@novapeak.com',
    items: [
      { id: 'item_seed_6a', description: 'SEO Optimization', quantity: 1, rate: 4800, type: 'service' },
      { id: 'item_seed_6b', description: 'Monthly Analytics Report', quantity: 3, rate: 400, type: 'service' },
    ],
    notes: 'Monthly retainer starting September.',
    paymentInstructions: 'Direct Deposit · ABA: 121000358 · Acct: 3344221100',
    dueDate: '2024-09-05',
    taxRate: 10,
    status: 'pending',
    createdAt: '2024-08-05T10:00:00.000Z',
  },
  {
    id: 'inv_seed_7',
    invoiceNumber: 'INV-0007',
    clientName: 'Lunar Labs',
    clientEmail: 'hello@lunarlabs.space',
    items: [
      { id: 'item_seed_7a', description: 'Data Analytics Dashboard', quantity: 1, rate: 7200, type: 'service' },
      { id: 'item_seed_7b', description: 'API Integration', quantity: 1, rate: 3400, type: 'service' },
    ],
    notes: 'Final payment upon delivery of milestone 3.',
    paymentInstructions: 'Wire Transfer · SWIFT: LUNARUS33 · Acct: 9988776655',
    dueDate: '2024-09-20',
    taxRate: 8,
    status: 'sent',
    createdAt: '2024-08-20T10:00:00.000Z',
  },
  {
    id: 'inv_seed_8',
    invoiceNumber: 'INV-0008',
    clientName: 'Vortex Media',
    clientEmail: 'accounts@vortexmedia.tv',
    items: [
      { id: 'item_seed_8a', description: 'Video Production Package', quantity: 1, rate: 5400, type: 'service' },
    ],
    notes: 'Includes 2 revision rounds.',
    paymentInstructions: '',
    dueDate: '2024-09-15',
    taxRate: 10,
    status: 'pending',
    createdAt: '2024-08-25T10:00:00.000Z',
  },
  {
    id: 'inv_seed_9',
    invoiceNumber: 'INV-0009',
    clientName: 'Summit Group',
    clientEmail: 'finance@summitgroup.com',
    items: [
      { id: 'item_seed_9a', description: 'Strategic Consulting', quantity: 10, rate: 250, type: 'service' },
    ],
    notes: '',
    paymentInstructions: 'Bank: SummitBank · Acct: 5566778899',
    dueDate: '2024-09-28',
    taxRate: 0,
    status: 'pending',
    createdAt: '2024-08-28T10:00:00.000Z',
  },
  {
    id: 'inv_seed_10',
    invoiceNumber: 'INV-0010',
    clientName: 'Apex Dev',
    clientEmail: 'dev@apex.dev',
    items: [
      { id: 'item_seed_10a', description: 'Custom CRM Development', quantity: 1, rate: 14500, type: 'service' },
      { id: 'item_seed_10b', description: 'Database Migration', quantity: 1, rate: 3200, type: 'service' },
    ],
    notes: 'Net-30 payment terms apply.',
    paymentInstructions: 'SWIFT: APEXUS44 · Acct: 1122334455',
    dueDate: '2024-10-05',
    taxRate: 8,
    status: 'pending',
    createdAt: '2024-09-05T10:00:00.000Z',
  },
  {
    id: 'inv_seed_11',
    invoiceNumber: 'INV-0011',
    clientName: 'Stellar Labs',
    clientEmail: 'finance@stellarlabs.io',
    items: [
      { id: 'item_seed_11a', description: 'AI Model Training Pipeline', quantity: 1, rate: 9200, type: 'service' },
      { id: 'item_seed_11b', description: 'Cloud GPU Setup', quantity: 1, rate: 2800, type: 'service' },
    ],
    notes: 'Milestone-based billing. First payment due on delivery.',
    paymentInstructions: 'Wire · SWIFT: STLRUS33 · Acct: 7766554433',
    dueDate: '2026-06-15',
    taxRate: 10,
    status: 'pending',
    createdAt: '2026-05-15T10:00:00.000Z',
  },
  {
    id: 'inv_seed_12',
    invoiceNumber: 'INV-0012',
    clientName: 'Meridian Health',
    clientEmail: 'ap@meridianhealth.com',
    items: [
      { id: 'item_seed_12a', description: 'Patient Portal Development', quantity: 1, rate: 16400, type: 'service' },
    ],
    notes: 'HIPAA compliance included. Net-30 terms.',
    paymentInstructions: 'ACH · Routing: 026009593 · Acct: 4433221100',
    dueDate: '2026-07-01',
    taxRate: 8,
    status: 'pending',
    createdAt: '2026-05-20T10:00:00.000Z',
  },
];

export const seedInvoices = () => {
  localStorage.setItem(STORAGE_KEYS.INVOICES, JSON.stringify(sampleInvoices));
};
